# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qrunom6q21u6-qgLfhbbBaEWAd_Fqgm0
"""

import Adafruit_DHT
import time
import pyrebase

config = {
    "apiKey": "AIzaSyAb-dXFIctuyzHKIhpI-D0xMI8eM_Ai3yk",
    "authDomain": "http://iot-assignment-31202.firebaseapp.com",
    "databaseURL": "your_database_urlhttps://iot-assignment-31202-default-rtdb.asia-southeast1.firebasedatabase.app",
    "storageBucket": "http://iot-assignment-31202.appspot.com"}

firebase = pyrebase.initialize_app(config)

db = firebase.database()

sensor = Adafruit_DHT.DHT11

pin = 4

while True:
    humidity, temperature = Adafruit_DHT.read_retry(sensor, pin)
    if humidity is not None and temperature is not None:
        print('Temp={0:0.1f}*C  Humidity={1:0.1f}%'.format(temperature, humidity))
        data = {"Temperature" : temperature, "Humidity" : humidity}
        db.child("Status").push(data)
        db.update(data)
        print("Sent to Firebase")
    else:
        print('Failed to get reading. Try again!')
    time.sleep(1)